export const Leaselist = [
    {
        id: "1",
        image: "/image/image1.jpeg",
        imagee: "/image/imagee1.jpeg",
        imager: "/image/imager1.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        dateOfHost: "Mar - Oct",
        date: "Mar - Oct",
        amount: 200000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Tulbagh city center in the very popular district.",
        HostImage: "/host1.jpg",
        hostName: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 6,
        bedroom: 3,
        bed: 5,
        bath: 3,
        years: 9,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "2",
        image: "/image/image2.jpg",
        imagee: "/image/imagee2.jpg",
        imager: "/image/imager2.jpeg",
        imaged: "/image/imaged2.jpeg",
        address: "El chaupi, Ecuador",
        view: "Viewed 15,177 times last week",
        date: "Apr - Nov",
        dateOfHost: "Mar - Oct",
        amount: 220000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of El chaupi city center in the very popular Ecuador district.",
        HostImage: "/host2.jpg",
        hostName: "Emmanuel & Yannis",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 5,
        bedroom: 4,
        bed: 4,
        bath: 3,
        years: 7,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "3",
        image: "/image/image3.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Brekenridge, Colorado, US",
        view: "Viewed 16,000 times last week",
        date: "Mar - Nov",
        amount: 250000,
        dateOfHost: "Mar - Oct",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Brekenridge city center in the very popular Colorado district.",
        hostImage: "/host3.jpg",
        hostName: "Kante",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 4.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 6,
        bedroom: 3,
        bed: 5,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "4",
        image: "/image/image4.jpg",
        imagee: "/image/imagee4.jpeg",
        imager: "/image/imager4.jpeg",
        imaged: "/image/imaged4.jpeg",
        address: "Cusco, Peru",
        view: "Viewed 14,277 times last week",
        date: "Apr - Oct",
        amount: 180000,
        dateOfHost: "Mar - Oct",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Cusco city center in the very popular Cusco district.",
        HostImage: "/host4.jpg",
        hostName: " Antonio J",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 6,
        bedroom: 3,
        bed: 5,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "5",
        image: "/image/image5.jpeg",
        imagee: "/image/imagee5.jpeg",
        imager: "/image/imager5.jpeg",
        imaged: "/image/imaged5.jpeg",
        address: "San juan, Ecuador",
        view: "Viewed 12,277 times last week",
        date: "Jan - Oct",
        amount: 200000,
        dateOfHost: "Mar - Oct",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of San juan city center in the very popular San juan district.",
        HostImage: "/host5.jpg",
        hostName: " Antonio",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 5,
        bedroom: 3,
        bed: 3,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "6",
        image: "/image/image6.jpeg",
        imagee: "/image/imagee2.jpg",
        imager: "/image/imager2.jpeg",
        imaged: "/image/imaged2.jpeg",
        address: "Aquitania, Colombia",
        view: "Viewed 14,277 times last week",
        date: "Mar - Oct",
        amount: 200000,
        dateOfHost: "Mar - Sept",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Aquitania city center in the very popular Aquitania district.",
        HostImage: "/host1.jpg",
        hostName: "Paez",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 5,
        bedroom: 3,
        bed: 4,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "7",
        image: "/image/image7.jpeg",
        imagee: "/image/image2.jpg",
        imager: "/image/image3.jpeg",
        imaged: "/image/image4.jpg",
        address: "Dillion, Colorado, US",
        view: "Viewed 12,177 times last week",
        date: "Mar - Sep",
        amount: 200000,
        dateOfHost: "Mar - Oct",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Dillion city center in the very popular Dillion district.",
        HostImage: "/host2.jpg",
        hostName: "John",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 4,
        bedroom: 3,
        bed: 3,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "8",
        image: "/image/image8.jpeg",
        imagee: "/image/imagee1.jpeg",
        imager: "/image/imager1.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Alma, Colorado, US",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 200000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Alma city center in the very popular Alma district.",
        HostImage: "/host1.jpg",
        hostName: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 4,
        bedroom: 3,
        bed: 3,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "9",
        image: "/image/image9.jpeg",
        imagee: "/image/imagee2.jpg",
        imager: "/image/imager2.jpeg",
        imaged: "/image/imaged2.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 200000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        hostName: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 4,
        bedroom: 3,
        bed: 3,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "10",
        image: "/image/image10.jpeg",
        imagee: "/image/image2.jpg",
        imager: "/image/image3.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        amount: 200000,
        dateOfHost: "Mar - Oct",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        hostName: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 4,
        bedroom: 3,
        bed: 3,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "11",
        image: "/image/image11.jpeg",
        imagee: "/image/imagee1.jpeg",
        imager: "/image/imager1.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 220000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        hostName: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 4.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 5,
        bedroom: 3,
        bed: 5,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "12",
        image: "/image/image12.jpeg",
        imagee: "/image/imagee2.jpg",
        imager: "/image/imager2.jpeg",
        imaged: "/image/imaged2.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        amount: 250000,
        dateOfHost: "Mar - Oct",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        hostName: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 4.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 3,
        bedroom: 3,
        bed: 3,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "13",
        image: "/image/image13.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 220000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        hostName: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 4,
        bedroom: 3,
        bed: 3,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "14",
        image: "/image/image14.jpeg",
        imagee: "/image/imagee4.jpeg",
        imager: "/image/imager4.jpeg",
        imaged: "/image/imaged4.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 220000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        hostName: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 3,
        bedroom: 3,
        bed: 3,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "15",
        image: "/image/image15.jpeg",
        imagee: "/image/imagee5.jpeg",
        imager: "/image/imager5.jpeg",
        imaged: "/image/imaged5.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 150000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 2,
        bedroom: 1,
        bed: 2,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "16",
        image: "/image/image16.jpeg",
        imagee: "/image/image2.jpg",
        imager: "/image/image3.jpeg",
        imaged: "/image/image4.jpg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        amount: 110000,
        dateOfHost: "Mar - Oct",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 2,
        bedroom: 1,
        bed: 1,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "17",
        image: "/image/image17.jpeg",
        imagee: "/image/image2.jpg",
        imager: "/image/image3.jpeg",
        imaged: "/image/image4.jpg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 100000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 3,
        bedroom: 3,
        bed: 3,
        bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "18",
        image: "/image/image18.jpeg",
        imagee: "/image/imagee1.jpeg",
        imager: "/image/imager1.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        amount: 120000,
        dateOfHost: "Mar - Oct",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 3,
        bedroom: 2,
        bed: 2,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "19",
        image: "/image/image19.jpeg",
        imagee: "/image/imagee2.jpg",
        imager: "/image/imager2.jpeg",
        imaged: "/image/imaged2.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        amount: 110000,
        dateOfHost: "Mar - Oct",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 2,
        bedroom: 1,
        bed: 2,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "20",
        image: "/image/image20.jpeg",
        imagee: "/image/image2.jpg",
        imager: "/image/image3.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 140000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 2,
        bedroom: 1,
        bed: 1,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "21",
        image: "/image/image21.jpeg",
        imagee: "/image/imagee1.jpeg",
        imager: "/image/imager1.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 150000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 2,
        bedroom: 2,
        bed: 2,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "22",
        image: "/image/image22.jpeg",
        imagee: "/image/imagee2.jpg",
        imager: "/image/imager2.jpeg",
        imaged: "/image/imaged2.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 130000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 3,
        bedroom: 2,
        bed: 2,
        bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "23",
        image: "/image/image23.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 200000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 2,
        bedroom: 1,
        bed: 1,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "24",
        image: "/image/image24.jpeg",
        imagee: "/image/imagee4.jpeg",
        imager: "/image/imager4.jpeg",
        imaged: "/image/imaged4.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        amount: 120000,
        dateOfHost: "Mar - Oct",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 2,
        bedroom: 1,
        bed: 1,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "25",
        image: "/image/image25.jpeg",
        imagee: "/image/imagee5.jpeg",
        imager: "/image/imager5.jpeg",
        imaged: "/image/imaged5.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 100000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 2,
        bedroom: 1,
        bed: 1,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "26",
        image: "/image/image26.jpeg",
        imagee: "/image/image2.jpg",
        imager: "/image/image3.jpeg",
        imaged: "/image/image4.jpg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 140000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 2,
        bedroom: 1,
        bed: 1,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "27",
        image: "/image/image27.jpeg",
        imagee: "/image/image2.jpg",
        imager: "/image/image3.jpeg",
        imaged: "/image/image4.jpg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        amount: 130000,
        dateOfHost: "Mar - Oct",
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 2,
        bedroom: 1,
        bed: 1,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "28",
        image: "/image/image28.jpeg",
        imagee: "/image/imagee1.jpeg",
        imager: "/image/imager1.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 200000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 2,
        bedroom: 1,
        bed: 1,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "29",
        image: "/image/image29.jpeg",
        imagee: "/image/imagee1.jpeg",
        imager: "/image/imager1.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 140000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 4,
        Bedroom: 1,
        Bed: 1,
        Bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "30",
        image: "/image/image30.jpg",
        imagee: "/image/image2.jpg",
        imager: "/image/image3.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 140000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        guests: 3,
        bedroom: 2,
        bed: 2,
        bath: 1,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "31",
        image: "/image/image31.jpeg",
        imagee: "/image/imagee1.jpeg",
        imager: "/image/imager1.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 110,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "32",
        image: "/image/image32.jpeg",
        imagee: "/image/imagee2.jpg",
        imager: "/image/imager2.jpeg",
        imaged: "/image/imaged2.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 120000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "33",
        image: "/image/image33.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 110000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "34",
        image: "/image/image34.jpeg",
        imagee: "/image/imagee4.jpeg",
        imager: "/image/imager4.jpeg",
        imaged: "/image/imaged4.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 110000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "35",
        image: "/image/image35.jpeg",
        imagee: "/image/imagee5.jpeg",
        imager: "/image/imager5.jpeg",
        imaged: "/image/imaged5.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 110000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "36",
        image: "/image/image36.jpeg",
        imagee: "/image/image2.jpeg",
        imager: "/image/image3.jpeg",
        imaged: "/image/image4.jpg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 110000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "37",
        image: "/image/image37.jpeg",
        imagee: "/image/image2.jpeg",
        imager: "/image/image3.jpeg",
        imaged: "/image/image4.jpg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 130000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 3,
        Bedroom: 2,
        Bed: 3,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "38",
        image: "/image/image38.jpeg",
        imagee: "/image/imagee1.jpeg",
        imager: "/image/imager1.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 200000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 5,
        Bedroom: 3,
        Bed: 5,
        Bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "39",
        image: "/image/image39.jpeg",
        imagee: "/image/imagee1.jpeg",
        imager: "/image/imager1.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 130000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 3,
        Bedroom: 2,
        Bed: 2,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "40",
        image: "/image/image40.jpeg",
        imagee: "/image/image2.jpg",
        imager: "/image/image3.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 110000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "41",
        image: "/image/image41.jpeg",
        imagee: "/image/imagee1.jpeg",
        imager: "/image/imager1.jpeg",
        imaged: "/image/imaged1.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 200000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 3,
        Bedroom: 2,
        Bed: 3,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "42",
        image: "/image/image42.jpeg",
        imagee: "/image/imagee2.jpg",
        imager: "/image/imager2.jpeg",
        imaged: "/image/imaged2.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 200000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "43",
        image: "/image/image43.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 200000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 3.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 6,
        Bedroom: 3,
        Bed: 5,
        Bath: 3,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "44",
        image: "/image/image44.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 130000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 3,
        Bedroom: 2,
        Bed: 2,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "45",
        image: "/image/image45.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 110000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "46",
        image: "/image/image46.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 110000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 2.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "47",
        image: "/image/image47.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 250000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 5.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "48",
        image: "/image/image48.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 250000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 5.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "49",
        image: "/image/image49.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 250000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 5.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 2,
        Bedroom: 1,
        Bed: 1,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
    {
        id: "50",
        image: "/image/image50.jpeg",
        imagee: "/image/imagee3.jpeg",
        imager: "/image/imager3.jpeg",
        imaged: "/image/imaged3.jpeg",
        address: "Tulbagh, South Africa",
        view: "Viewed 14,177 times last week",
        date: "Mar - Oct",
        dateOfHost: "Mar - Oct",
        amount: 250000,
        about: "Enjoy an elegant 20 m2 private room in a renovated 160 m2 apartment in the heart of Nantes city center in the very popular Graslin district.",
        HostImage: "/host1.jpg",
        name: "Romain",
        location: "Saint-Helena, France",
        message: "Warm welcome, I recommend, easy to walk to restaurants and bars",
        rating: 5.0,
        // let the weeks pik the day the host hosted the property
        weeks: "2 weeks ago",
        Guests: 3,
        Bedroom: 2,
        Bed: 3,
        Bath: 2,
        years: 6,
        service: 27000,
        cleaning: 45000,
    },
]